# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 911a27c2ab5058f0c104c08d67903673e75c37289762540aa19d423597c8d147e34387d2f45c9084c19ba2779dc4526844466d4e1d9c2b67653b1d4d5aac6d5d

test:
  secret_key_base: 5d9a1c07d88139a2f186f33a138e0426c6f114da8b1fb72926ecd4c17ccf6b040bf37cb41ef28ed833cf3adc54433d840d085a8a97572510c9b30b2bbc0f3c3f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
